[package]
name = "gametank-emu-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13.0"
winit = { version = "0.29.10", features = ["rwh_05"]}
winit_input_helper = "0.15.3"
log = { version = "0.4.20", features = [] }
env_logger = "0.11.2"
