[package]
name = "gametank-emu-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
pixels = "0.13.0"
winit = { version = "0.29.10", features = ["rwh_05"]}
winit_input_helper = "0.15.3"
log = { version = "0.4.20", features = [] }
env_logger = "0.11.2"
futures = "0.3.30"
wasm-bindgen = "0.2.91"
#wasm-bindgen-futures = "0.4.41"
web-sys = { version = "0.3.68", features = ["Performance"] }
console_log = "1.0.0"
console_error_panic_hook = "0.1"
bit_field = "0.10.2"
bitfield = "0.14.0"
rand = { version = "0.8.5" }
getrandom = { version = "0.2.12", features = ["js"] }
#emulator_6502 = "1.1.0"
simple_logger = "4.3.3"

w65c02s = "0.9.2"
wee_alloc = "0.4.5"